### ISSUE TITLE
A distribution for python 3 support.

### ISSUE THREAD

**Issue by MagIciaNGTAO** [six8/pytailer#5]
Looks like the one we have doesn't support python3.

https://pypi.python.org/pypi/tailer

**Comment by svetlyak40wt** [comment]
Actually, version from github supports Python3 and a pull request was merged in 2013: https://github.com/six8/pytailer/pull/4

But there wasn't PyPi release after that.

You only need to increment a version number and to upload another release.

**Comment by dsuch** [comment]
Hello,

yes - can you please create a new release? The current one on PyPI, 0.3, does not include Python 3-specific patches and won't work on Python 3.

This is only a matter of issuing the following command having first increased version to 0.4.

```
$ python setup.py sdist upload
```

Cheers!

**Comment by dsuch** [comment]
Hi there,

since there has been no response from the author for several days, I have forked the project and released the Python 3-compatible version on PyPI under tailer-py3:

https://pypi.python.org/pypi/tailer-py3

I will be most happy to delete it if there is a Python 3-ready release of tailer itself, but until then, this is what I will be using because I really, really needed a PyPI release.

Cheers.

**Comment by six8** [comment]
Sorry for the delay, I updated the version and deployed 0.4 to https://pypi.python.org/pypi/tailer/0.4

**Comment by dsuch** [comment]
@six8 - I have deleted https://pypi.python.org/pypi/tailer-py3 in that case. Thanks!
